language: node_js
notifications:
  email:
    recipients:
      - nickjohnson.dev@gmail.com
node_js: 10
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn lint
  - yarn build
  - yarn test --coverage
before_deploy:
  - npx codecov
  - yarn migrate
deploy:
  provider: heroku
  cleanup: true
  edge: true
  on:
    branch: master
